// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PresetsColumns holds the columns for the "presets" table.
	PresetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "display", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_positive", Type: field.TypeBool},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PresetsTable holds the schema information for the "presets" table.
	PresetsTable = &schema.Table{
		Name:       "presets",
		Columns:    PresetsColumns,
		PrimaryKey: []*schema.Column{PresetsColumns[0]},
	}
	// ReviewsColumns holds the columns for the "reviews" table.
	ReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "target_id", Type: field.TypeString},
		{Name: "rating", Type: field.TypeUint8},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ReviewsTable holds the schema information for the "reviews" table.
	ReviewsTable = &schema.Table{
		Name:       "reviews",
		Columns:    ReviewsColumns,
		PrimaryKey: []*schema.Column{ReviewsColumns[0]},
	}
	// ReviewPresetsColumns holds the columns for the "review_presets" table.
	ReviewPresetsColumns = []*schema.Column{
		{Name: "review_id", Type: field.TypeInt},
		{Name: "preset_id", Type: field.TypeInt},
	}
	// ReviewPresetsTable holds the schema information for the "review_presets" table.
	ReviewPresetsTable = &schema.Table{
		Name:       "review_presets",
		Columns:    ReviewPresetsColumns,
		PrimaryKey: []*schema.Column{ReviewPresetsColumns[0], ReviewPresetsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "review_presets_review_id",
				Columns:    []*schema.Column{ReviewPresetsColumns[0]},
				RefColumns: []*schema.Column{ReviewsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "review_presets_preset_id",
				Columns:    []*schema.Column{ReviewPresetsColumns[1]},
				RefColumns: []*schema.Column{PresetsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PresetsTable,
		ReviewsTable,
		ReviewPresetsTable,
	}
)

func init() {
	ReviewPresetsTable.ForeignKeys[0].RefTable = ReviewsTable
	ReviewPresetsTable.ForeignKeys[1].RefTable = PresetsTable
}
