// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Preset is the predicate function for preset builders.
type Preset func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)
